var EMpId = 12;
var EmployeeName = "Scott";
var EmployeeJob = "Manager";
var IsPermanantEmployee = true;
var EmployeeSalary = "INR 20000";
var DeptNo = 10;
console.log("Employee Id:", EMpId);
console.log("Employee Name:", EmployeeName);
console.log("Employee Job title:", EmployeeJob);
console.log("ThisIsPermanantEmployee:", IsPermanantEmployee);
console.log("Employee Salary:", EmployeeSalary);
console.log("Employee Department Id:", DeptNo);
console.log("------------------------------------------------------------------");
console.log("Employee Id: ".concat(EMpId, ", Employee Name: ").concat(EmployeeName, ", Employee Job: ").concat(EmployeeJob, " ,ThisIsPermanantEmployee: ").concat(IsPermanantEmployee, ",Employee Salary: ").concat(EmployeeSalary, ",Employee Department Id: ").concat(DeptNo));
